% % MATH 151A HOMEWORK1 
% % QUESTION 5
% % Wang, Zheng (404855295)
% % Results are recorded in homework1.pdf

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Secant Method to solve f(x) = sin(x)-x = 0  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% initialize
i = 2;
p0 = pi/4;
p1 = 3*pi/8;
q0 = f(p0);
q1 = f(p1);
arr_p = [];
arr_it = [];

% Set the max iteration number
N = 10000;

% Set the tolerance
TO = 10^(-5);


%iteration
while i <= N
    p = p1 - q1*(p1-p0)/(q1-q0);
    % stopping condition
    if abs(p - p1) < TO
        fprintf('The solution using secant method is %e at iteration #%d\n', p, i)
        break;
    end
    i = i+1;
    p0 = p1;
    q0 = q1;
    p1 = p;
    q1 = f(p);
    arr_p = [arr_p p];
    arr_it = [arr_it i];
end

% output the failure message if needed
if i > N
fprintf('Secant Method failed after %d iteration, the value found is %e\n',N, p)
end

% plot the graph
figure;
plot(arr_it, arr_p, 'o-r', 'Linewidth', 1.1);
title('\{p_n\} Generated by Secant Method (for n >= 2)');
xlabel('iteration number')
ylabel('p_n')
grid on;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Newton's Method to solve f(x) = sin(x)-x = 0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% initialize
i = 1;
p0 = pi/4;
q0 = f(p0);
d0 = fprim(p0);
arr_p = [];
arr_it = [];


% Set the max iteration number
N = 10000;

% Set the tolerance
TO = 10^(-5);

%iteration
while i <= N
    p = p0 - q0/d0;
    if abs(p - p0) < TO
        fprintf('The solution of Newton''s method is %e at iteration #%d\n', p, i)
        break;
    end
    i = i+1;
    p0 = p;
    arr_p = [arr_p p0];
    arr_it = [arr_it i];
    q0 = f(p0);
    d0 = fprim(p);
end

% output the failure message if needed
if i > N
fprintf('Newton''s Method failed after %d iteration, the value found is %e\n',N, p)
end

% plot the graph
figure;
plot(arr_it, arr_p, 'o-', 'Linewidth', 1.1);
title('\{p_n\} Generated by Newton''s Method (for n >= 1)');
xlabel('iteration number')
ylabel('p_n')
grid on;

% % function declaration
function y = f(x)
    y = sin(x) - x;
end

function y = fprim(x)
    y = cos(x) - 1;
end